[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.0"
async-graphql = "7.0.5"
async-graphql-actix-web = "7.0.5"
actix-web = "4.0"
tokio = { version = "1", features = ["full"] } #async runtime
serde_json = "1.0"